#For all profiles

server:
 port: 9050
spring:
 application:
  name: service-cliente
 jpa:
  show-sql: true

#dev
---
spring:
 profiles: dev
 datasource:
  url: jdbc:mysql://localhost:3306/dbbanco
  username: root
  password: admin


#docker
---
spring:
 profiles: docker
 datasource:
  url: jdbc:mysql://host.docker.internal:3306/dbbanco
  username: root
  password: admin 