server:
 port: 9030
spring:
 application:
  name: service-movimiento
 jpa:
  show-sql: true
 datasource:
  url: jdbc:mysql://localhost:3306/dbbanco
  username: root
  password: admin

cuenta:
 url: http://localhost:9040/api/cuentas

cliente:
 url: http://localhost:9050/api/clientes